server-name=City Lobby
motd=Selamat datang di City Lobby
gamemode=adventure
difficulty=easy
max-players=20
server-port=19132
level-name=Maharlika_City
level-seed=
online-mode=true
white-list=false
allow-list=false
allow-cheats=true
enable-command-block=false
enable-command-block-admins-only=true
auto-save=true
allow-flight=true
view-distance=12
tick-distance=4
spawn-monsters=false
spawn-npcs=false
spawn-animals=true
spawn-villagers=true
force-gamemode=true
texturepack-required=false
player-idle-timeout=30
server-authoritative-movement=true
server-authoritative-dismount=false
content-log-file-enabled=false
